import {frameLocal} from '../cad/planes'
import {beforeAll,expect,it} from 'vitest'
import {readFileSync} from 'node:fs'
import initOpenCascade from 'opencascade.js/dist/node.js'
import type {OpenCascadeInstance} from 'opencascade.js'
import {applyCommand,createDocument,parseProject,serializeProject} from '../cad/document'
import {buildModel} from '../cad/kernel'
import {rectangleEntities,sketchRegions} from '../cad/sketch-entities'
import type {SketchEntity} from '../cad/types'
let oc:OpenCascadeInstance
beforeAll(async()=>{oc=await initOpenCascade({module:{wasmBinary:readFileSync(new URL('../../node_modules/opencascade.js/dist/opencascade.full.wasm',import.meta.url))}})})
function sketch(entities:SketchEntity[]){return applyCommand(createDocument('Entities','mm'),{type:'feature',feature:{type:'sketch',parameters:{plane:'XY',x:0,y:0,width:20,height:20,entities}}})}
it('extrudes one chosen region and keeps the region ID after save/reload',()=>{const entities=[...rectangleEntities([0,0],[20,10],'a'),...rectangleEntities([30,0],[35,5],'b')],region=sketchRegions(entities)[1];let doc=sketch(entities);doc=applyCommand(doc,{type:'feature',feature:{type:'extrude',parameters:{profileId:doc.features[0].id,regionId:region.id,distance:10,operation:'new'}}});const model=buildModel(oc,parseProject(serializeProject(doc)));expect(model.volume).toBeCloseTo(250,5);expect(model.bounds.min[0]).toBeCloseTo(30,5)})
it('makes an exact circular hole from nested sketch boundaries',()=>{const entities:SketchEntity[]=[...rectangleEntities([0,0],[20,20],'a'),{id:'circle',type:'circle',center:[10,10],radius:3}],region=sketchRegions(entities).find(r=>r.holes.length)!;let doc=sketch(entities);doc=applyCommand(doc,{type:'feature',feature:{type:'extrude',parameters:{profileId:doc.features[0].id,regionId:region.id,distance:10,operation:'new'}}});expect(buildModel(oc,doc).volume).toBeCloseTo((400-Math.PI*9)*10,5)})
it('keeps a three-point arc analytic when extruded',()=>{const entities:SketchEntity[]=[{id:'arc',type:'arc',start:[5,0],mid:[0,5],end:[-5,0]},{id:'line',type:'line',start:[-5,0],end:[5,0]}];let doc=sketch(entities);doc=applyCommand(doc,{type:'feature',feature:{type:'extrude',parameters:{profileId:doc.features[0].id,regionId:sketchRegions(entities)[0].id,distance:10,operation:'new'}}});expect(buildModel(oc,doc).volume).toBeCloseTo(Math.PI*25/2*10,5)})
it('rejects a removed selected region rather than switching to a different profile',()=>{const entities=rectangleEntities([0,0],[20,20],'a');let doc=sketch(entities);doc=applyCommand(doc,{type:'feature',feature:{type:'extrude',parameters:{profileId:doc.features[0].id,regionId:'region:missing',distance:10,operation:'new'}}});expect(()=>buildModel(oc,doc)).toThrow(/region.*missing|region.*unavailable|reselect/i)})

it('retains an old extrusion when its sketch gains multiple regions',()=>{let doc=applyCommand(createDocument('Legacy','mm'),{type:'feature',feature:{type:'sketch',parameters:{plane:'XY',x:0,y:0,width:20,height:20}}});doc=applyCommand(doc,{type:'feature',feature:{type:'extrude',parameters:{profileId:doc.features[0].id,distance:10,operation:'new'}}});const entities=[...rectangleEntities([0,0],[20,20],'original'),...rectangleEntities([30,0],[35,5],'new')];doc=applyCommand(doc,{type:'feature',id:doc.features[0].id,feature:{type:'sketch',parameters:{plane:'XY',x:0,y:0,width:35,height:20,entities,defaultRegionId:sketchRegions(entities)[0].id}}});expect(buildModel(oc,parseProject(serializeProject(doc))).volume).toBeCloseTo(4000,5)})

it('revolves a selected entity region around the Y axis',()=>{const entities=[...rectangleEntities([5,0],[10,6],'r'),...rectangleEntities([20,0],[25,4],'other')];let doc=sketch(entities);doc=applyCommand(doc,{type:'feature',feature:{type:'revolve',parameters:{profileId:doc.features[0].id,regionId:sketchRegions(entities)[0].id,axis:'Y',axisOffset:0,angle:360,operation:'new'}}});expect(buildModel(oc,doc).volume).toBeCloseTo(Math.PI*75*6,5)})
it('uses the original circle for hole placement after sketch conversion',()=>{let doc=applyCommand(createDocument('Hole','mm'),{type:'feature',feature:{type:'sketch',parameters:{plane:'XY',x:0,y:0,width:20,height:20}}});doc=applyCommand(doc,{type:'feature',feature:{type:'extrude',parameters:{profileId:doc.features[0].id,distance:20,operation:'new'}}});const entities:SketchEntity[]=[{id:'circle',type:'circle',center:[10,10],radius:2},...rectangleEntities([30,0],[40,10],'extra')];doc=applyCommand(doc,{type:'feature',feature:{type:'sketch',parameters:{plane:'XY',x:8,y:0,width:32,height:12,profile:'circle',entities,defaultRegionId:sketchRegions(entities)[0].id}}});doc=applyCommand(doc,{type:'feature',feature:{type:'hole',parameters:{bodyId:doc.features[1].id,profileId:doc.features[2].id,plane:'XY',x:0,y:0,diameter:1,offset:20,depth:20}}});expect(buildModel(oc,doc).volume).toBeCloseTo(8000-Math.PI*4*20,5)})

it('keeps a multi-entity face layer attached after editing the base height',()=>{let doc=applyCommand(createDocument('Layer','mm'),{type:'feature',feature:{type:'sketch',parameters:{plane:'XY',x:0,y:0,width:20,height:20}}});doc=applyCommand(doc,{type:'feature',feature:{type:'extrude',parameters:{profileId:doc.features[0].id,distance:20,operation:'new'}}});const base=doc.features[1],face=buildModel(oc,doc).faces.find(f=>f.normal?.[2]===1)!,c=frameLocal(face.frame!,face.center),entities:SketchEntity[]=[...rectangleEntities([c[0]-5,c[1]-5],[c[0]+5,c[1]+5],'boss'),{id:'bore',type:'circle',center:[c[0],c[1]],radius:2}];doc=applyCommand(doc,{type:'feature',feature:{type:'sketch',parameters:{plane:'XY',x:c[0]-5,y:c[1]-5,width:10,height:10,entities,support:face.reference!}}});doc=applyCommand(doc,{type:'feature',feature:{type:'extrude',parameters:{profileId:doc.features[2].id,bodyId:base.id,regionId:sketchRegions(entities)[0].id,distance:5,operation:'join'}}});if(base.type!=='extrude')throw Error('base');doc=applyCommand(doc,{type:'feature',id:base.id,feature:{type:'extrude',parameters:{...base.parameters,distance:30}}});const model=buildModel(oc,parseProject(serializeProject(doc)));expect(model.volume).toBeCloseTo(12000+(100-Math.PI*4)*5,5);expect(model.bounds.max[2]).toBeCloseTo(35,5)})
