import {beforeAll,it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import initOpenCascade from 'opencascade.js/dist/node.js'
import type {OpenCascadeInstance} from 'opencascade.js'
import type {CadDocument,FeatureInput} from '../cad/types'
import {applyCommand,createDocument,parseProject,serializeProject,dependentFeatures} from '../cad/document'
import {buildModel} from '../cad/kernel'
let oc:OpenCascadeInstance
beforeAll(async()=>{oc=await initOpenCascade({module:{wasmBinary:readFileSync(new URL('../../node_modules/opencascade.js/dist/opencascade.full.wasm',import.meta.url))}})})
const add=(d:CadDocument,f:FeatureInput)=>applyCommand(d,{type:'feature',feature:f})
const base=()=>{let d=add(createDocument('Tools','mm'),{type:'sketch',parameters:{plane:'XY',x:0,y:0,width:20,height:10}});return add(d,{type:'extrude',parameters:{distance:30}})}
it('creates exact box, cylinder and sphere B-Rep primitives and round-trips them',()=>{let d=createDocument('Primitives','mm');d=add(d,{type:'box',parameters:{x:0,y:0,z:0,width:20,depth:10,height:30,operation:'new'}});d=add(d,{type:'cylinder',parameters:{x:40,y:0,z:0,diameter:10,height:20,axis:'X',operation:'new'}});d=add(d,{type:'sphere',parameters:{x:100,y:0,z:0,diameter:10,operation:'new'}});const m=buildModel(oc,parseProject(serializeProject(d)));expect(m.bodies).toHaveLength(3);expect(m.volume).toBeCloseTo(6000+Math.PI*25*20+4/3*Math.PI*125,4);expect(m.bodies![1].bounds.max[0]).toBeCloseTo(60,4)})
it('primitive cut modifies only its chosen target and follows upstream edits',()=>{let d=base();d=add(d,{type:'cylinder',parameters:{bodyId:d.features[1].id,x:10,y:5,z:0,diameter:4,height:30,axis:'Z',operation:'cut'}});expect(buildModel(oc,d).volume).toBeCloseTo(6000-Math.PI*4*30,4);expect(dependentFeatures(d,d.features[1].id)).toHaveLength(2)})
it('rotates a body about an explicit pivot without changing volume or source body identity',()=>{let d=base();const bodyId=d.features[1].id;d=add(d,{type:'rotate',parameters:{bodyId,axis:'Z',angle:90,x:10,y:5,z:0,copy:false}});const m=buildModel(oc,d);expect(m.volume).toBeCloseTo(6000,4);expect(m.bodies![0].id).toBe(bodyId);expect(m.bounds.min[0]).toBeCloseTo(5,4);expect(m.bounds.min[1]).toBeCloseTo(-5,4);expect(m.bounds.max[0]).toBeCloseTo(15,4);expect(m.bounds.max[1]).toBeCloseTo(15,4)})
it('uniform scale uses its pivot and retains editable independent copies',()=>{let d=base();const bodyId=d.features[1].id;d=add(d,{type:'scale',parameters:{bodyId,factor:2,x:10,y:5,z:15,copy:true}});const m=buildModel(oc,parseProject(serializeProject(d)));expect(m.bodies).toHaveLength(2);expect(m.bodies![0].volume).toBeCloseTo(6000,4);expect(m.bodies![1].volume).toBeCloseTo(48000,3);expect(m.bodies![1].bounds.min[0]).toBeCloseTo(-10,4);expect(m.bodies![1].id).toBe(d.features.at(-1)!.id+':copy:1');d=add(d,{type:'move',parameters:{bodyId:m.bodies![1].id,x:50,y:0,z:0}});expect(buildModel(oc,d).bodies).toHaveLength(2)})
it('splits a solid into independent closed bodies with conserved volume and stable references',()=>{let d=base();const bodyId=d.features[1].id;d=add(d,{type:'split',parameters:{bodyId,plane:'XY',offset:12,keep:'both'}});const m=buildModel(oc,d);expect(m.bodies).toHaveLength(2);expect(m.volume).toBeCloseTo(6000,4);expect(m.bodies!.map(b=>Math.round(b.volume)).sort((a,b)=>a-b)).toEqual([2400,3600]);expect(m.bodies![0].id).toBe(bodyId);const copy=m.bodies![1].id;d=add(d,{type:'move',parameters:{bodyId:copy,x:25,y:0,z:0}});expect(buildModel(oc,parseProject(serializeProject(d))).bodies![1].bounds.min[0]).toBeCloseTo(25,4);expect(dependentFeatures(d,d.features[2].id).map(f=>f.type)).toEqual(['split','move'])})
it('split keep-side honors the negative Y normal of XZ and reference-plane edits',()=>{let d=base();d=add(d,{type:'plane',parameters:{plane:'XZ',offset:-4}});const planeId=d.features.at(-1)!.id;d=add(d,{type:'split',parameters:{bodyId:d.features[1].id,plane:'XY',planeId,offset:0,keep:'positive'}});expect(buildModel(oc,d).volume).toBeCloseTo(20*4*30,4);d=applyCommand(d,{type:'feature',id:planeId,feature:{type:'plane',parameters:{plane:'XZ',offset:-6}}});expect(buildModel(oc,d).volume).toBeCloseTo(20*6*30,4)})
it('rejects tangent or missing split planes and zero/negative scale without altering the document',()=>{const d=base(),before=serializeProject(d);expect(()=>buildModel(oc,add(d,{type:'split',parameters:{bodyId:d.features[1].id,plane:'XY',offset:30,keep:'both'}}))).toThrow(/intersect|cross|split/i);for(const factor of [0,-1,NaN])expect(()=>add(d,{type:'scale',parameters:{bodyId:d.features[1].id,factor,x:0,y:0,z:0,copy:false}})).toThrow(/factor/i);expect(serializeProject(d)).toBe(before)})
it('copies rotation without consuming the source and supports negative angles',()=>{let d=base();d=add(d,{type:'rotate',parameters:{bodyId:d.features[1].id,axis:'Y',angle:-90,x:0,y:0,z:0,copy:true}});const m=buildModel(oc,d);expect(m.bodies).toHaveLength(2);expect(m.volume).toBeCloseTo(12000,4);expect(m.bodies![1].bounds.min[0]).toBeCloseTo(-30,4)})

it('scale expressions reject length units and follow dimensionless parameter edits',()=>{let d=base();d=applyCommand(d,{type:'parameters',values:{ratio:'2'}});d=add(d,{type:'scale',parameters:{bodyId:d.features[1].id,factor:2,x:0,y:0,z:0,copy:false},expressions:{factor:'ratio'}});expect(buildModel(oc,d).volume).toBeCloseTo(48000,3);d=applyCommand(d,{type:'parameters',values:{ratio:'0.5'}});expect(buildModel(oc,d).volume).toBeCloseTo(750,4);expect(()=>applyCommand(d,{type:'parameters',values:{ratio:'2 mm'}})).toThrow(/units/i)})
