import {test,expect} from '@playwright/test'
test('persistent radius constraint survives conflict, local history, extrusion and reload',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click()
 await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click()
 await page.getByRole('button',{name:'Circle',exact:true}).click();await page.getByRole('button',{name:'Constrain sketch',exact:true}).click()
 await page.getByRole('button',{name:'Select circle 1',exact:true}).press('Enter')
 await page.getByLabel('Constraint type',{exact:true}).selectOption('radius');await page.getByLabel('Constraint value',{exact:true}).fill('10');await page.getByRole('button',{name:'Add constraint',exact:true}).click()
 await expect(page.getByTestId('constraint-status')).toContainText('2 degrees of freedom')
 await expect(page.getByRole('list',{name:'Sketch constraints'})).toContainText('Radius')
 await page.getByLabel('Constraint value',{exact:true}).fill('15');await page.getByRole('button',{name:'Add constraint',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText(/conflict/i);await expect(page.getByRole('list',{name:'Sketch constraints'}).getByRole('listitem')).toHaveCount(1)
 await page.getByRole('button',{name:'Undo sketch',exact:true}).click();await expect(page.getByRole('list',{name:'Sketch constraints'}).getByRole('listitem')).toHaveCount(0)
 await page.getByRole('button',{name:'Redo sketch',exact:true}).click();await expect(page.getByRole('list',{name:'Sketch constraints'}).getByRole('listitem')).toHaveCount(1)
 await page.screenshot({path:info.outputPath('sketch-constraints.png')})
 await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByLabel('Distance',{exact:true}).fill('12');await page.getByRole('button',{name:'Apply',exact:true}).click()
 await expect(page.getByTestId('model-volume')).toHaveText('3769.911 mm³')
 await page.reload();await expect(page.getByTestId('model-volume')).toHaveText('3769.911 mm³');await page.getByRole('button',{name:'Sketch 1',exact:true}).click();await page.getByRole('button',{name:'Constrain sketch',exact:true}).click()
 await expect(page.getByRole('list',{name:'Sketch constraints'})).toContainText('Radius')
 await page.getByLabel('Edit Radius constraint',{exact:true}).fill('12');await page.getByLabel('Edit Radius constraint',{exact:true}).press('Enter')
 await expect(page.getByTestId('constraint-status')).toContainText('2 degrees of freedom');await page.getByRole('button',{name:'Finish sketch',exact:true}).click()
 await expect(page.getByTestId('model-volume')).toHaveText('5428.672 mm³');expect(errors).toEqual([])
})
