import {test,expect,type Page} from '@playwright/test'
async function openCircle(page:Page){await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByLabel('Profile type',{exact:true}).selectOption('circle');await page.getByLabel('Diameter',{exact:true}).fill('20')}
test('a primitive circle dimension can be placed by dragging its edge and edited without losing its saved placement',async({page},info)=>{
 await openCircle(page);await page.getByRole('button',{name:'Dimension',exact:true}).click();const edge=page.getByRole('button',{name:'Circular sketch edge',exact:true}),p=await edge.evaluate(el=>{const path=el as SVGPathElement,point=path.getPointAtLength(0),out=new DOMPoint(point.x,point.y).matrixTransform(path.getScreenCTM()!);return {x:out.x,y:out.y}});await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+135,p.y-100,{steps:6});await page.mouse.up();const label=page.getByRole('button',{name:'Edit diameter dimension',exact:true}),placed=await label.boundingBox();await label.click();await page.getByLabel('Dimension value',{exact:true}).fill('5');await page.getByRole('button',{name:'Set dimension',exact:true}).click();await expect(label).toContainText('5.000 mm');await page.screenshot({path:info.outputPath('placed-circle-dimension.png')});await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Sketch 1',exact:true}).click();const restored=await label.boundingBox();expect(restored!.x).toBeCloseTo(placed!.x,0);expect(restored!.y).toBeCloseTo(placed!.y,0);await expect(label).toContainText('5.000 mm');
})
test('multi-entity circle gets a draggable editable dimension and extrudes its exact diameter',async({page},info)=>{
 await openCircle(page);await page.getByRole('button',{name:'More sketch tools',exact:true}).click();await page.getByRole('button',{name:'Dimension',exact:true}).click();const edge=page.getByRole('button',{name:'Select circle 1',exact:true}),p=await edge.evaluate(el=>{const path=el as SVGPathElement,v=path.getPointAtLength(0),out=new DOMPoint(v.x,v.y).matrixTransform(path.getScreenCTM()!);return {x:out.x,y:out.y}});await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+140,p.y-100,{steps:6});await page.mouse.up();const label=page.getByRole('button',{name:/Edit sketch dimension/});await label.press('Enter');await page.getByLabel('Sketch dimension value',{exact:true}).fill('5');await page.getByRole('button',{name:'Set sketch dimension',exact:true}).click();await expect(label).toContainText('5.000 mm');await label.click();await expect(page.getByLabel('Sketch dimension value',{exact:true})).toHaveValue('5');await page.getByRole('button',{name:'Cancel dimension',exact:true}).click();const finish=await page.getByRole('button',{name:'Finish sketch',exact:true}).boundingBox();expect(finish!.x+finish!.width).toBeLessThanOrEqual(page.viewportSize()!.width);await page.screenshot({path:info.outputPath('entity-diameter-dimension.png')});await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByLabel('Distance',{exact:true}).fill('5');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('98.175 mm³');await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Sketch 1',exact:true}).click();await expect(label).toContainText('5.000 mm');
})
test('selecting a circular solid edge exposes a draggable exact diameter callout',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await openCircle(page);await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByLabel('Distance',{exact:true}).fill('5');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('1570.796 mm³');await page.getByRole('button',{name:'TOP',exact:true}).click();await page.getByRole('button',{name:'Measure',exact:true}).click();const canvas=page.getByLabel('3D model viewport. Drag to orbit, right-drag to pan, scroll to zoom.',{exact:true}),box=await canvas.boundingBox();await canvas.click({position:{x:box!.width/2+box!.height/3.6,y:box!.height/2}});const label=page.getByRole('button',{name:'Drag edge measurement',exact:true});await expect(label).toHaveText('Ø 20.000 mm');const before=await label.boundingBox();await page.mouse.move(before!.x+before!.width/2,before!.y+before!.height/2);await page.mouse.down();await page.mouse.move(before!.x+before!.width/2-80,before!.y+before!.height/2-60,{steps:6});await page.mouse.up();const after=await label.boundingBox();expect(after!.x).toBeLessThan(before!.x-60);await expect(page.getByTestId('model-volume')).toHaveText('1570.796 mm³');await page.getByRole('button',{name:'Switch to dark mode',exact:true}).click();await page.screenshot({path:info.outputPath('solid-edge-measurement.png')});expect(errors).toEqual([])
})
