import {test,expect,type Page} from '@playwright/test'
async function open(page:Page){await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await expect(page.getByRole('button',{name:'Create sketch',exact:true})).toBeEnabled()}
async function box(page:Page){await open(page);await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('24000.000 mm³')}
async function dragAndType(page:Page,handleName:string,inputName:string,value:string){
 const handle=page.getByRole('button',{name:handleName,exact:true});await expect(handle).toBeVisible();const b=await handle.boundingBox();await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2);await page.mouse.down();await page.mouse.move(b!.x+b!.width/2+12,b!.y+b!.height/2-18,{steps:4});await page.keyboard.press('Tab');const input=page.getByRole('textbox',{name:inputName,exact:true});await expect(input).toBeFocused();await input.fill(value);await page.mouse.up();await expect(input).toHaveValue(value);await input.press('Enter');await expect(page.getByText('FEATURE PREVIEW',{exact:true})).toBeVisible()
}
test('extrusion arrow supports Tab numeric entry during drag, including a second face layer',async({page})=>{
 await box(page);await page.getByRole('button',{name:'Extrude 1',exact:true}).click();await dragAndType(page,'Drag extrusion distance','Canvas distance','24');await expect(page.getByLabel('Distance',{exact:true})).toHaveValue('24');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('36000.000 mm³')
 await page.getByRole('button',{name:'TOP',exact:true}).click();const canvas=page.getByLabel('3D model viewport. Drag to orbit, right-drag to pan, scroll to zoom.',{exact:true});const b=await canvas.boundingBox();await canvas.click({position:{x:b!.width/2,y:b!.height/2}});await page.getByRole('button',{name:'Sketch on face',exact:true}).click();await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();await dragAndType(page,'Drag extrusion distance','Canvas distance','7');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('36700.000 mm³')
})
test('chamfer and fillet expose editable arrow handles on selected edges',async({page},info)=>{
 await box(page);await page.getByRole('button',{name:'Chamfer',exact:true}).click();await page.getByRole('checkbox',{name:'Select chamfer edge 1',exact:true}).check();await dragAndType(page,'Drag chamfer distance','Canvas chamfer distance','2');await expect(page.getByLabel('Chamfer distance',{exact:true})).toHaveValue('2');await page.screenshot({path:info.outputPath('chamfer-direct-input.png')});await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByRole('button',{name:'Chamfer 1',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('24000.000 mm³');await page.getByRole('button',{name:'Fillet',exact:true}).click();await page.getByRole('checkbox',{name:'Select edge 1',exact:true}).check();await dragAndType(page,'Drag fillet radius','Canvas radius','2');await expect(page.getByLabel('Radius',{exact:true})).toHaveValue('2');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByRole('button',{name:'Fillet 1',exact:true})).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0)
})
test('sketch drag accepts Tab width and height without pointer release overwriting typed values',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();const canvas=page.getByRole('img',{name:'Rectangle sketch drawing surface'});const b=await canvas.boundingBox();await page.mouse.move(b!.x+200,b!.y+220);await page.mouse.down();await page.mouse.move(b!.x+310,b!.y+290,{steps:4});await page.keyboard.press('Tab');const width=page.getByRole('textbox',{name:'Canvas width',exact:true});await expect(width).toBeFocused();await width.fill('42');await width.press('Tab');const height=page.getByRole('textbox',{name:'Canvas height',exact:true});await expect(height).toBeFocused();await height.fill('18');await page.mouse.up();await height.press('Enter');await expect(page.getByLabel('Width',{exact:true})).toHaveValue('42');await expect(page.getByLabel('Height',{exact:true})).toHaveValue('18');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('12096.000 mm³')
})

test('canvas values support units, invalid input recovery and local Escape',async({page})=>{
 await box(page);await page.getByRole('button',{name:'Extrude 1',exact:true}).click();const input=page.getByRole('textbox',{name:'Canvas distance',exact:true});await input.fill('invalid');await input.press('Enter');await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('24000.000 mm³');await page.getByRole('button',{name:'Extrude 1',exact:true}).click();await input.fill('1 in');await input.press('Enter');await expect(page.getByText('FEATURE PREVIEW',{exact:true})).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0);await input.fill('7');await input.press('Escape');await expect(page.getByLabel('Distance',{exact:true})).toHaveValue('1 in');await expect(page.getByRole('button',{name:'Apply',exact:true})).toBeVisible();await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('38100.000 mm³')
})

test('other numeric tools accept Tab entry and a reference plane can start a sketch',async({page})=>{
 await box(page);await page.getByRole('button',{name:'Search commands Ctrl K',exact:true}).click();await page.getByLabel('Search commands',{exact:true}).fill('Reference plane');await page.getByRole('dialog',{name:'Command search'}).getByRole('button').filter({has:page.getByText('Reference plane',{exact:true})}).click();await page.keyboard.press('Tab');const offset=page.getByRole('textbox',{name:'Canvas plane offset',exact:true});await expect(offset).toBeFocused();await offset.fill('12');await offset.press('Enter');await expect(page.getByText('FEATURE PREVIEW',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByRole('button',{name:'Reference plane 1',exact:true})).toBeVisible();await page.getByRole('button',{name:'Sketch',exact:true}).click();await page.getByRole('group',{name:'Sketch plane selection'}).getByRole('button',{name:'Reference plane 1',exact:true}).click();await expect(page.getByLabel('Reference plane',{exact:true})).toHaveValue(/.+/);await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('48000.000 mm³')
})


test('negative canvas extrusion cuts a circular pocket and a through hole with saved history',async({page},info)=>{
 await box(page);await page.getByRole('button',{name:'TOP',exact:true}).click();const canvas=page.getByLabel('3D model viewport. Drag to orbit, right-drag to pan, scroll to zoom.',{exact:true});const b=await canvas.boundingBox();await canvas.click({position:{x:b!.width/2,y:b!.height/2}});await page.getByRole('button',{name:'Sketch on face',exact:true}).click();await page.getByRole('toolbar',{name:'Sketch tools'}).getByRole('button',{name:'Circle',exact:true}).click();await page.getByLabel('Origin X',{exact:true}).fill('25');await page.getByLabel('Origin Y',{exact:true}).fill('15');await page.getByLabel('Diameter',{exact:true}).fill('10');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();
 const input=page.getByRole('textbox',{name:'Canvas distance',exact:true});await input.fill('-5');await page.getByLabel('Extrude operation',{exact:true}).selectOption('cut');await expect(page.getByLabel('Extrusion direction',{exact:true})).toHaveValue('forward');await input.press('Enter');await expect(page.getByText('FEATURE PREVIEW',{exact:true})).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0);await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('23607.301 mm³');await page.reload();await expect(page.getByTestId('model-volume')).toHaveText('23607.301 mm³');await page.getByRole('button',{name:'Extrude 2',exact:true}).click();await expect(input).toHaveValue('-5');await page.getByLabel('Distance',{exact:true}).fill('-16');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('22743.363 mm³');await page.screenshot({path:info.outputPath('negative-extrude-through-hole.png')});await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('23607.301 mm³');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('22743.363 mm³');
})
