import { test,expect } from '@playwright/test'
async function ready(page:import('@playwright/test').Page){await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0)}
test('draw on a selected solid face, join a boss, edit support and reload',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await ready(page)
 await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page);await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await ready(page)
 await page.getByRole('button',{name:'TOP',exact:true}).click();const canvas=page.getByLabel('3D model viewport. Drag to orbit, right-drag to pan, scroll to zoom.',{exact:true});const b=await canvas.boundingBox();await canvas.click({position:{x:b!.width/2,y:b!.height/2}})
 await page.getByRole('button',{name:'Sketch on face',exact:true}).click();await expect(page.getByText('Attached to Extrude 1',{exact:true})).toBeVisible();await expect(page.getByTestId('sketch-model-context')).toBeVisible()
 const tools=page.getByRole('toolbar',{name:'Sketch tools'});await tools.getByRole('button',{name:'Circle',exact:true}).click();await expect(tools.getByRole('button',{name:'Circle',exact:true}).locator('svg')).toBeVisible()
 const surface=page.getByRole('img',{name:'Circle sketch drawing surface'});const box=await surface.boundingBox();await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2);await page.mouse.down();await page.mouse.move(box!.x+box!.width/2+35,box!.y+box!.height/2,{steps:5});await page.mouse.up();expect(Number(await page.getByLabel('Diameter',{exact:true}).inputValue())).toBeGreaterThan(0)
 await page.getByLabel('Origin X',{exact:true}).fill('25');await page.getByLabel('Origin Y',{exact:true}).fill('15');await page.getByLabel('Diameter',{exact:true}).fill('10');await page.screenshot({path:info.outputPath('sketch-on-face.png')});await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page)
 await page.getByRole('button',{name:'Extrude',exact:true}).click();await expect(page.getByLabel('Extrude operation',{exact:true})).toHaveValue('join');await page.getByLabel('Distance',{exact:true}).fill('5');await page.getByRole('button',{name:'Apply',exact:true}).click();await ready(page);await expect(page.getByTestId('model-volume')).toHaveText('24392.699 mm³')
 await page.getByRole('button',{name:'Extrude 1',exact:true}).click();await page.getByLabel('Distance',{exact:true}).fill('25');await page.getByRole('button',{name:'Apply',exact:true}).click();await ready(page);await expect(page.getByTestId('model-volume')).toHaveText('37892.699 mm³');await page.reload();await expect(page.getByTestId('model-volume')).toHaveText('37892.699 mm³');await page.screenshot({path:info.outputPath('face-boss-workspace.png')});expect(errors).toEqual([])
})

test('Sketch can pick a support face after starting the command and cut a side pocket',async({page},info)=>{
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await ready(page)
 await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page);await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await ready(page)
 await page.getByRole('button',{name:'Sketch',exact:true}).click();await page.getByRole('button',{name:'RIGHT',exact:true}).click()
 const canvas=page.getByLabel('3D model viewport. Drag to orbit, right-drag to pan, scroll to zoom.',{exact:true});const b=await canvas.boundingBox();await canvas.click({position:{x:b!.width/2,y:b!.height/2}});await expect(page.getByText('Attached to Extrude 1',{exact:true})).toBeVisible()
 await page.getByRole('toolbar',{name:'Sketch tools'}).getByRole('button',{name:'Circle',exact:true}).click();await page.getByLabel('Origin X',{exact:true}).fill('15');await page.getByLabel('Origin Y',{exact:true}).fill('8');await page.getByLabel('Diameter',{exact:true}).fill('6');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page)
 await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByLabel('Extrude operation',{exact:true}).selectOption('cut');await expect(page.getByLabel('Extrusion direction',{exact:true})).toHaveValue('reverse');await page.getByLabel('Distance',{exact:true}).fill('5');await page.getByRole('button',{name:'Apply',exact:true}).click();await ready(page);await expect(page.getByTestId('model-volume')).toHaveText('23858.628 mm³');await page.screenshot({path:info.outputPath('side-face-pocket.png')})
})


test('canceling a sketch retains the camera and projection',async({page},info)=>{
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await ready(page)
 await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page);await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await ready(page)
 await expect(page.getByTestId('model-volume')).toHaveText('24000.000 mm³');await page.getByRole('button',{name:'RIGHT',exact:true}).click();await page.getByLabel('Projection',{exact:true}).selectOption('perspective');await page.mouse.move(20,20)
 // Hide the complete cube overlay (including its shadow) to compare camera pixels independently of DOM antialiasing.
 const canvas=page.getByLabel('3D model viewport. Drag to orbit, right-drag to pan, scroll to zoom.',{exact:true});const before=await canvas.screenshot({path:info.outputPath('camera-before.png'),animations:'disabled',style:'.orientation-widget{visibility:hidden!important}'})
 await page.getByRole('button',{name:'Sketch',exact:true}).click();await page.getByRole('button',{name:'Cancel sketch',exact:true}).click();await page.mouse.move(20,20)
 await expect(page.getByLabel('Projection',{exact:true})).toHaveValue('perspective');expect((await canvas.screenshot({path:info.outputPath('camera-after.png'),animations:'disabled',style:'.orientation-widget{visibility:hidden!important}'})).equals(before)).toBe(true)
})
