import {test,expect,type Page} from '@playwright/test'
async function block(page:Page){
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('24000.000 mm³')
}
test('counterbore and countersink edit, preview, undo and reload as solid features',async({page})=>{
 await block(page);await page.getByRole('button',{name:'Hole',exact:true}).click();await expect(page.getByLabel('Hole style',{exact:true})).toBeVisible({timeout:2000});await page.getByLabel('Hole style',{exact:true}).selectOption('counterbore')
 await page.getByLabel('Hole diameter',{exact:true}).fill('4');await page.getByLabel('Hole depth',{exact:true}).fill('10');await page.getByLabel('Recess diameter',{exact:true}).fill('8');await page.getByLabel('Counterbore depth',{exact:true}).fill('3')
 await page.getByRole('button',{name:'Preview geometry',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('23761.239 mm³')
 await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Hole 1',exact:true}).click();await expect(page.getByLabel('Hole style',{exact:true})).toHaveValue('counterbore')
 await page.getByLabel('Hole style',{exact:true}).selectOption('countersink');await page.getByLabel('Countersink angle',{exact:true}).fill('90');await page.getByLabel('Hole termination',{exact:true}).selectOption('through-all');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('23765.428 mm³')
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('23761.239 mm³');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('23765.428 mm³')
})
test('two shell openings make an editable open tube without losing saved face references',async({page})=>{
 await block(page);await page.getByRole('button',{name:'All tools',exact:true}).click();await page.getByRole('dialog',{name:'CAD tools'}).getByRole('button',{name:'Shell',exact:true}).click();await expect(page.getByRole('group',{name:'Shell openings'})).toBeVisible({timeout:2000})
 await page.getByLabel('Shell opening +Z',{exact:true}).check();await page.getByLabel('Shell opening −Z',{exact:true}).check();await page.getByLabel('Wall thickness',{exact:true}).fill('2');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('4864.000 mm³')
 await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Shell 1',exact:true}).click();await expect(page.getByText('2 openings selected',{exact:true})).toBeVisible();await page.getByLabel('Wall thickness',{exact:true}).fill('3');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('7104.000 mm³')
})
