import { test,expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
async function ready(page:Page){await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0)}
async function command(page:Page,name:string){await page.getByRole('button',{name:'Search commands Ctrl K',exact:true}).click();await page.getByLabel('Search commands',{exact:true}).fill(name);await page.getByRole('dialog',{name:'Command search'}).getByRole('button').filter({has:page.getByText(name,{exact:true})}).click()}
async function apply(page:Page,name:string){await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByRole('button',{name,exact:true})).toBeVisible();await ready(page)}
test('industrial solid workflow, editable gear, reload history and STEP/STL exports',async({page},info)=>{
 test.setTimeout(600000)
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByLabel('Project name',{exact:true}).fill('Industrial acceptance');await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await ready(page)
 await command(page,'Sketch');await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByLabel('Width',{exact:true}).fill('80');await page.getByLabel('Height',{exact:true}).fill('60');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page)
 await command(page,'Extrude');await page.getByLabel('Distance',{exact:true}).fill('20');await apply(page,'Extrude 1')
 await command(page,'Sketch');await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByLabel('Profile type',{exact:true}).selectOption('circle');await page.getByLabel('Origin X',{exact:true}).fill('15');await page.getByLabel('Origin Y',{exact:true}).fill('15');await page.getByLabel('Diameter',{exact:true}).fill('8');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page)
 await command(page,'Hole');await page.getByLabel('Hole start offset',{exact:true}).fill('20');await page.getByLabel('Hole depth',{exact:true}).fill('20');await apply(page,'Hole 1')
 await command(page,'Fillet');await page.getByTitle('Length 20.000 mm · midpoint 0.000 mm, 0.000 mm, 10.000 mm',{exact:true}).getByRole('checkbox').check();await page.getByLabel('Radius',{exact:true}).fill('3');await apply(page,'Fillet 1')
 await command(page,'Chamfer');await page.getByTitle('Length 60.000 mm · midpoint 80.000 mm, 30.000 mm, 0.000 mm',{exact:true}).getByRole('checkbox').check();await page.getByLabel('Chamfer distance',{exact:true}).fill('2');await apply(page,'Chamfer 1')
 await page.getByRole('button',{name:'Faces',exact:true}).click();await page.getByRole('button',{name:'TOP',exact:true}).click();const canvas=page.getByLabel('3D model viewport. Drag to orbit, right-drag to pan, scroll to zoom.',{exact:true});const bounds=await canvas.boundingBox();await canvas.click({position:{x:bounds!.width/2,y:bounds!.height/2}});await expect(page.getByRole('heading',{name:'Selected face',exact:true})).toBeVisible()
 await command(page,'Shell');await page.getByLabel('Wall thickness',{exact:true}).fill('1');await apply(page,'Shell 1')
 await command(page,'Reference plane');await page.getByLabel('Base plane',{exact:true}).selectOption('XZ');await page.getByLabel('Plane offset',{exact:true}).fill('100');await apply(page,'Reference plane 1')
 await command(page,'Sketch');await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByLabel('Reference plane',{exact:true}).selectOption({label:'Reference plane 1'});await page.getByLabel('Origin X',{exact:true}).fill('10');await page.getByLabel('Origin Y',{exact:true}).fill('0');await page.getByLabel('Width',{exact:true}).fill('5');await page.getByLabel('Height',{exact:true}).fill('10');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page)
 await command(page,'Revolve');await page.getByLabel('Revolve axis',{exact:true}).selectOption('Z');await apply(page,'Revolve 1')
 await command(page,'Linear pattern');await page.getByLabel('Source body',{exact:true}).selectOption({label:'Revolve 1'});await page.getByLabel('Pattern axis',{exact:true}).selectOption('X');await page.getByLabel('Spacing',{exact:true}).fill('50');await apply(page,'Linear pattern 1')
 // A separate pair of intersecting bodies tests target/tool ownership without consuming the shelled part.
 await command(page,'Sketch');await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByLabel('Origin X',{exact:true}).fill('180');await page.getByLabel('Width',{exact:true}).fill('20');await page.getByLabel('Height',{exact:true}).fill('20');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page)
 await command(page,'Extrude');await page.getByLabel('Distance',{exact:true}).fill('20');await apply(page,'Extrude 2')
 await command(page,'Sketch');await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByLabel('Origin X',{exact:true}).fill('190');await page.getByLabel('Width',{exact:true}).fill('20');await page.getByLabel('Height',{exact:true}).fill('20');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page)
 await command(page,'Extrude');await page.getByLabel('Distance',{exact:true}).fill('20');await apply(page,'Extrude 3')
 await command(page,'Combine');await page.getByLabel('Target body',{exact:true}).selectOption({label:'Extrude 2'});for(const box of await page.getByRole('group',{name:'Tool bodies'}).getByRole('checkbox').all()) await box.uncheck();await page.getByRole('group',{name:'Tool bodies'}).getByLabel('Extrude 3',{exact:true}).check();await apply(page,'Combine 1')
 await command(page,'Spur gear');await page.getByLabel('Gear X',{exact:true}).fill('270');await page.getByLabel('Module',{exact:true}).fill('2');await page.getByLabel('Teeth',{exact:true}).fill('24');await page.getByLabel('Pressure angle',{exact:true}).fill('20');await page.getByLabel('Gear thickness',{exact:true}).fill('10');await page.getByLabel('Bore diameter',{exact:true}).fill('8');await apply(page,'Spur gear 1');await expect(page.getByTestId('gear-pitch-diameter')).toHaveText('48.000 mm')
 await page.getByRole('button',{name:'Spur gear 1',exact:true}).click();await page.getByLabel('Teeth',{exact:true}).fill('30');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('gear-pitch-diameter')).toHaveText('60.000 mm');await ready(page)
 await page.reload();await expect(page.getByTestId('gear-pitch-diameter')).toHaveText('60.000 mm');await ready(page)
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByTestId('gear-pitch-diameter')).toHaveText('48.000 mm');await ready(page)
 await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.getByTestId('gear-pitch-diameter')).toHaveText('60.000 mm');await ready(page)
 await page.screenshot({path:info.outputPath('industrial-workspace.png')})
 await command(page,'Export');await page.getByLabel('Exchange format',{exact:true}).selectOption('step');const stepWait=page.waitForEvent('download',{timeout:90000});await page.getByRole('button',{name:'Export STEP',exact:true}).click();const step=await stepWait;await step.saveAs(info.outputPath('acceptance.step'));expect((await readFile(info.outputPath('acceptance.step'),'utf8')).slice(0,500)).toContain('ISO-10303-21')
 await page.getByLabel('Exchange format',{exact:true}).selectOption('stl');const stlWait=page.waitForEvent('download',{timeout:90000});await page.getByRole('button',{name:'Export STL',exact:true}).click();await expect(page.getByText(/Download ready/)).toBeVisible({timeout:90000});const stl=await stlWait;await stl.saveAs(info.outputPath('acceptance.stl'));const bytes=await readFile(info.outputPath('acceptance.stl'));expect(bytes.length).toBe(84+50*bytes.readUInt32LE(80));expect(errors).toEqual([])
})
