import { test,expect } from '@playwright/test'
test('CAD shortcuts, exact dimensions, contextual menus and cancellation',async({page})=>{
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click()
 await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Sketch',exact:true})).toBeEnabled();await page.keyboard.press('s');await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await expect(page.getByRole('button',{name:'Finish sketch',exact:true})).toBeVisible()
 await page.keyboard.press('d');await page.getByRole('button',{name:'Edit width dimension',exact:true}).click()
 await page.getByLabel('Dimension value',{exact:true}).fill('64');await page.getByRole('button',{name:'Set dimension',exact:true}).click()
 await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.keyboard.press('e');await page.getByRole('button',{name:'Apply',exact:true}).click()
 await expect(page.getByTestId('model-volume')).toContainText('30720.000')
 await page.keyboard.press('Control+k');await page.getByLabel('Search commands',{exact:true}).fill('chamfer');await expect(page.getByRole('dialog',{name:'Command search'}).getByRole('button',{name:/Chamfer/})).toBeVisible();await page.keyboard.press('Escape')
 await page.getByRole('button',{name:'Sketch 1',exact:true}).click({button:'right'});await expect(page.getByRole('menuitem',{name:/Edit feature/})).toBeVisible();await page.keyboard.press('Escape')
})

async function selectCommand(page:import('@playwright/test').Page,name:string){await page.getByRole('button',{name:'Search commands Ctrl K',exact:true}).click();await page.getByLabel('Search commands',{exact:true}).fill(name);await page.getByRole('dialog',{name:'Command search'}).getByRole('button').filter({has:page.getByText(name,{exact:true})}).click()}
test('named sketch dimensions survive edits, a parameter rebuild and reload',async({page})=>{
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible()
 await selectCommand(page,'Parameters');await page.getByLabel('Parameter definitions',{exact:true}).fill('span = 40 mm');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible()
 await selectCommand(page,'Sketch');await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByLabel('Width',{exact:true}).fill('span');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible()
 await selectCommand(page,'Extrude');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('19200.000 mm³')
 await page.getByRole('button',{name:'Sketch 1',exact:true}).click();await expect(page.getByLabel('Width',{exact:true})).toHaveValue('span');await page.getByLabel('Height',{exact:true}).fill('20');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('12800.000 mm³')
 await selectCommand(page,'Parameters');await page.getByLabel('Parameter definitions',{exact:true}).fill('span = 60 mm');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('19200.000 mm³');await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.reload();await expect(page.getByTestId('model-volume')).toHaveText('19200.000 mm³')
})
test('reverse and symmetric extrusion plus planar push/pull remain editable',async({page})=>{
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible()
 await selectCommand(page,'Sketch');await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await selectCommand(page,'Extrude');await page.getByLabel('Extrusion direction',{exact:true}).selectOption('reverse');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('24000.000 mm³')
 await page.getByRole('button',{name:'Extrude 1',exact:true}).click();await page.getByLabel('Extrusion direction',{exact:true}).selectOption('symmetric');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'TOP',exact:true}).click();const canvas=page.getByLabel('3D model viewport. Drag to orbit, right-drag to pan, scroll to zoom.',{exact:true});const box=await canvas.boundingBox();await canvas.click({position:{x:box!.width/2,y:box!.height/2}});await page.getByRole('button',{name:'Push / pull face',exact:true}).click();await page.getByLabel('Face offset',{exact:true}).fill('4');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('30000.000 mm³')
 await page.getByRole('button',{name:'Push/pull 1',exact:true}).click();await page.getByLabel('Face offset',{exact:true}).fill('-2');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('21000.000 mm³');await expect(page.getByRole('alert')).toHaveCount(0)
})
