import {test,expect,type Page} from '@playwright/test'
async function ready(page:Page){await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0)}
async function open(page:Page){await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await ready(page)}
async function command(page:Page,name:string){await page.getByRole('button',{name:'Search commands Ctrl K',exact:true}).click();await page.getByLabel('Search commands',{exact:true}).fill(name);await page.getByRole('dialog',{name:'Command search'}).getByRole('button').filter({has:page.getByText(name,{exact:true})}).click()}
async function circle(page:Page,diameter:string,reference=false){await command(page,'Sketch');await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();if(reference)await page.getByLabel('Reference plane',{exact:true}).selectOption({label:'Reference plane 1'});await page.getByLabel('Profile type',{exact:true}).selectOption('circle');await page.getByLabel('Diameter',{exact:true}).fill(diameter);await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page)}
async function point(page:Page,x:number,y:number){return page.getByRole('img',{name:'Multi-profile sketch drawing surface'}).evaluate((el,p)=>{const svg=el as SVGSVGElement,scale=Number(svg.dataset.scale),out=new DOMPoint(Number(svg.dataset.originX)+p[0]*scale,Number(svg.dataset.originY)-p[1]*scale).matrixTransform(svg.getScreenCTM()!);return {x:out.x,y:out.y}},[x,y])}
test('Loft preview, ordered sections, edit, saved history and automatic sketch hiding',async({page},info)=>{
 await open(page);await circle(page,'20');await command(page,'Reference plane');await page.getByLabel('Plane offset',{exact:true}).fill('30');await page.getByRole('button',{name:'Apply',exact:true}).click();await ready(page);await circle(page,'10',true);await page.getByRole('button',{name:'Loft',exact:true}).click();await page.getByLabel('Ruled transitions',{exact:true}).check();await expect(page.locator('.model-viewport-layer .viewport')).toHaveAttribute('data-visible-sketches','2');await page.getByRole('button',{name:'Preview geometry',exact:true}).click();await expect(page.getByText('FEATURE PREVIEW',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('loft-preview.png')});await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('button',{name:'Loft 1',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Loft',exact:true}).click();await page.getByLabel('Ruled transitions',{exact:true}).check();await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('5497.787 mm³');await expect(page.locator('.model-viewport-layer .viewport')).toHaveAttribute('data-visible-sketches','0');await page.getByRole('button',{name:'Reference plane 1',exact:true}).click();await page.getByLabel('Plane offset',{exact:true}).fill('45');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('8246.681 mm³');await ready(page);await page.reload();await expect(page.getByTestId('model-volume')).toHaveText('8246.681 mm³');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('5497.787 mm³');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('8246.681 mm³');await ready(page);
})
test('Sweep uses a drawn path and preserves a valid model when preview is cancelled',async({page},info)=>{
 await open(page);await circle(page,'4');await command(page,'Sketch');await page.getByRole('button',{name:'Sketch on XZ plane',exact:true}).click();await page.getByRole('button',{name:'More sketch tools',exact:true}).click();await page.getByRole('button',{name:'Clear sketch',exact:true}).click();await page.getByRole('button',{name:'Line',exact:true}).click();for(const xy of [[0,0],[0,30]]){const p=await point(page,...xy as [number,number]);await page.mouse.click(p.x,p.y)}await page.keyboard.press('Escape');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await ready(page);await page.getByRole('button',{name:'Sweep',exact:true}).click();await expect(page.getByLabel('Sweep profile',{exact:true}).locator('option:checked')).toHaveText('Sketch 1');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('376.991 mm³');await expect(page.locator('.model-viewport-layer .viewport')).toHaveAttribute('data-visible-sketches','0');await page.screenshot({path:info.outputPath('sweep-solid.png')});await page.getByRole('button',{name:'Sweep 1',exact:true}).click();await page.getByRole('button',{name:'Preview geometry',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('376.991 mm³');await ready(page);await page.reload();await expect(page.getByTestId('model-volume')).toHaveText('376.991 mm³');
})
