import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('rectangle → solid → fillet → resize → history → reopen → validated STL', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByText('B-Rep geometry · valid solid')).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.screenshot({path:testInfo.outputPath('landing-desktop.png'),fullPage:true})
  await page.getByRole('button',{name:'Open workspace',exact:true}).click()
  await page.getByLabel('Project name',{exact:true}).fill('Milestone verification')
  await page.getByRole('dialog',{name:'Create a new project'}).getByRole('button',{name:'Create project',exact:true}).click()
  await expect(page.getByRole('button',{name:'XY plane',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click()
  const sketchSurface=page.getByRole('img',{name:'Rectangle sketch drawing surface'})
  const drawing=await sketchSurface.boundingBox()
  await page.mouse.move(drawing!.x+drawing!.width*.3,drawing!.y+drawing!.height*.6)
  await page.mouse.down()
  await page.mouse.move(drawing!.x+drawing!.width*.55,drawing!.y+drawing!.height*.35,{steps:8})
  await page.mouse.up()
  await expect(page.getByLabel('Width',{exact:true})).not.toHaveValue('0')
  await page.getByLabel('Origin X',{exact:true}).fill('0')
  await page.getByLabel('Origin Y',{exact:true}).fill('0')
  await page.getByLabel('Width',{exact:true}).fill('50')
  await page.getByLabel('Height',{exact:true}).fill('30')
  await page.getByRole('button',{name:'Finish sketch',exact:true}).click()
  await page.getByRole('button',{name:'Extrude sketch',exact:true}).click()
  await page.getByLabel('Distance',{exact:true}).fill('16')
  await page.getByRole('button',{name:'Preview geometry',exact:true}).click()
  await expect(page.getByText('FEATURE PREVIEW',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Cancel',exact:true}).click()
  await expect(page.getByRole('button',{name:'Extrude sketch',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Extrude sketch',exact:true}).click()
  await page.getByRole('button',{name:'Apply',exact:true}).click()
  await expect(page.getByTestId('model-volume')).toContainText('24000.000')
  const canvas=page.getByLabel('3D model viewport. Drag to orbit, right-drag to pan, scroll to zoom.',{exact:true})
  const bounds=await canvas.boundingBox()
  expect(bounds).toBeTruthy()
  const cx=bounds!.x+bounds!.width/2, cy=bounds!.y+bounds!.height/2
  await page.mouse.move(cx,cy);await page.mouse.down();await page.mouse.move(cx+90,cy+45,{steps:12});await page.mouse.up()
  await page.getByRole('button',{name:'TOP',exact:true}).click()
  await canvas.click({position:{x:bounds!.width/2,y:bounds!.height/2}})
  await expect(page.getByRole('heading',{name:'Selected face',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Edges',exact:true}).click()
  await canvas.click({position:{x:bounds!.width/2,y:bounds!.height/3}})
  await expect(page.getByRole('heading',{name:'Selected edge',exact:true})).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'Home view',exact:true}).click()
  await page.getByRole('button',{name:'Fillet',exact:true}).click()
  await page.getByLabel('Select edge 1',{exact:true}).check()
  await page.getByLabel('Radius',{exact:true}).fill('100')
  await page.getByRole('button',{name:'Apply',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText(/Fillet/i)
  await expect(page.getByRole('button',{name:'Fillet 1',exact:true})).toHaveCount(0)
  await page.getByLabel('Radius',{exact:true}).fill('2')
  await page.getByRole('button',{name:'Apply',exact:true}).click()
  await expect(page.getByRole('button',{name:'Fillet 1',exact:true})).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  const originalVolume=await page.getByTestId('model-volume').innerText()
  await page.getByRole('button',{name:'Sketch 1',exact:true}).click()
  await page.getByLabel('Width',{exact:true}).fill('60')
  await page.getByRole('button',{name:'Finish sketch',exact:true}).click()
  await expect(page.getByTestId('model-volume')).not.toHaveText(originalVolume)
  const resizedVolume=await page.getByTestId('model-volume').innerText()
  await page.getByRole('button',{name:'Undo',exact:true}).click()
  await expect(page.getByTestId('model-volume')).toHaveText(originalVolume)
  await page.getByRole('button',{name:'Redo',exact:true}).click()
  await expect(page.getByTestId('model-volume')).toHaveText(resizedVolume)
  await expect(page.getByText('Saved locally',{exact:true})).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('model-volume')).toHaveText(resizedVolume)
  await expect(page.getByRole('button',{name:'Fillet 1',exact:true})).toBeVisible()
  await page.screenshot({path:testInfo.outputPath('editor-desktop.png')})
  const backupWait=page.waitForEvent('download')
  await page.getByRole('button',{name:'Download editable backup',exact:true}).click()
  const backup=await backupWait
  const backupPath=testInfo.outputPath('milestone.anishape')
  await backup.saveAs(backupPath)
  const saved=JSON.parse(await readFile(backupPath,'utf8'))
  expect(saved.document.features).toHaveLength(3)
  expect(saved.document.features[0].parameters.width).toBe(60)
  await page.getByRole('button',{name:'Export',exact:true}).click()
  const downloadWait=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export STL',exact:true}).click()
  const download=await downloadWait
  const stlPath=testInfo.outputPath('milestone.stl')
  await download.saveAs(stlPath)
  const bytes=await readFile(stlPath)
  const triangles=bytes.readUInt32LE(80)
  expect(triangles).toBeGreaterThan(12)
  expect(bytes.length).toBe(84+50*triangles)
  await expect(page.getByText(/closed manifold mesh/)).toBeVisible()
  await page.getByRole('button',{name:'Close',exact:true}).click()
  await page.getByRole('button',{name:'Milestone verification',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Local projects',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Open project',exact:true}).click()
  await expect(page.getByTestId('model-volume')).toHaveText(resizedVolume)
  await page.getByRole('button',{name:'Milestone verification',exact:true}).click()
  await page.getByLabel('Open .anishape',{exact:true}).setInputFiles(backupPath)
  await expect(page.getByRole('button',{name:'Milestone verification (imported)',exact:true})).toBeVisible()
  await expect(page.getByTestId('model-volume')).toHaveText(resizedVolume)
  expect(errors).toEqual([])
})

test('mobile landing has usable navigation without horizontal overflow', async ({page},testInfo)=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await expect(page.getByRole('heading',{level:1})).toBeVisible()
  await expect(page.getByText('B-Rep geometry · valid solid')).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:testInfo.outputPath('landing-mobile.png'),fullPage:true})
  await page.getByRole('button',{name:'Try without account',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Create a new project'})).toBeVisible()
})

test('drag extrusion, cancel/apply, redesigned cube, feature deletion and project deletion',async({page},testInfo)=>{
  await page.goto('/#projects')
  await page.getByRole('button',{name:'New project',exact:true}).click()
  await page.getByLabel('Project name',{exact:true}).fill('Manipulation verification')
  await page.getByRole('dialog',{name:'Create a new project'}).getByRole('button',{name:'Create project',exact:true}).click()
  await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click()
  await page.getByRole('button',{name:'Finish sketch',exact:true}).click()
  await page.getByRole('button',{name:'Extrude sketch',exact:true}).click()
  const handle=page.getByRole('button',{name:'Drag extrusion distance',exact:true})
  await expect(handle).toBeVisible()
  const box=await handle.boundingBox()
  await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2)
  await page.mouse.down()
  await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2-70,{steps:12})
  await page.mouse.up()
  await expect(page.getByText('FEATURE PREVIEW',{exact:true})).toBeVisible()
  expect(Number(await page.getByLabel('Distance',{exact:true}).inputValue())).toBeGreaterThan(16)
  await page.screenshot({path:testInfo.outputPath('extrusion-arrow.png')})
  await page.getByRole('button',{name:'Cancel',exact:true}).click()
  await expect(page.getByRole('button',{name:'Extrude sketch',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Extrude sketch',exact:true}).click()
  await handle.focus()
  await page.keyboard.press('ArrowUp')
  await expect(page.getByLabel('Distance',{exact:true})).toHaveValue('17')
  await expect(page.getByText('FEATURE PREVIEW',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Apply',exact:true}).click()
  await expect(page.getByTestId('model-volume')).toHaveText('25500.000 mm³')
  await page.getByRole('button',{name:'TOP',exact:true}).click()
  await expect(page.getByRole('button',{name:'TOP',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.getByRole('button',{name:'Delete Sketch 1',exact:true}).click()
  const deletion=page.getByRole('dialog',{name:'Delete feature',exact:true})
  await expect(deletion.getByText('Extrude 1',{exact:true})).toBeVisible()
  await deletion.getByRole('button',{name:'Delete feature',exact:true}).click()
  await expect(page.getByRole('button',{name:'Create sketch',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Undo',exact:true}).click()
  await expect(page.getByTestId('model-volume')).toHaveText('25500.000 mm³')
  await expect(page.getByText('Saved locally',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Manipulation verification',exact:true}).click()
  await page.getByRole('button',{name:'Delete project Manipulation verification',exact:true}).click()
  const projectDeletion=page.getByRole('dialog',{name:'Delete local project',exact:true})
  await projectDeletion.getByRole('button',{name:'Delete project',exact:true}).click()
  await expect(page.getByRole('heading',{name:'A clean slate.',exact:true})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading',{name:'A clean slate.',exact:true})).toBeVisible()
})