import {test,expect,type Page} from '@playwright/test'
async function open(page:Page){await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByRole('button',{name:'Add more sketch geometry',exact:true}).click()}
async function point(page:Page,x:number,y:number){return page.getByRole('img',{name:'Multi-profile sketch drawing surface'}).evaluate((el,p)=>{const svg=el as SVGSVGElement,m=svg.getScreenCTM()!,scale=Number(svg.dataset.scale);const out=new DOMPoint(Number(svg.dataset.originX)+p[0]*scale,Number(svg.dataset.originY)-p[1]*scale).matrixTransform(m);return {x:out.x,y:out.y}},[x,y])}
async function click(page:Page,x:number,y:number){const p=await point(page,x,y);await page.mouse.click(p.x,p.y)}
async function drag(page:Page,x:number,y:number,ex:number,ey:number){const a=await point(page,x,y),b=await point(page,ex,ey);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:4});await page.mouse.up()}
async function extrude(page:Page,region:number){await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByLabel('Extrude region',{exact:true}).selectOption({index:region});await page.getByLabel('Distance',{exact:true}).fill('10');await page.getByRole('button',{name:'Apply',exact:true}).click()}
test('multiple regions, inner hole, construction geometry and persistent entity editing',async({page},info)=>{
 await open(page);await expect(page.locator('.sketch-state')).toContainText('4 entities');await page.getByRole('button',{name:'Circle',exact:true}).click();await drag(page,25,15,30,15);await page.getByRole('button',{name:'Rectangle',exact:true}).click();await drag(page,65,0,75,10);await page.getByRole('button',{name:'Construction',exact:true}).click();await page.getByRole('button',{name:'Line',exact:true}).click();await click(page,0,0);await click(page,50,30);await page.keyboard.press('Escape');await expect(page.locator('.sketch-state')).toContainText('10 entities');await expect(page.locator('.sketch-state')).toContainText('3 regions');await page.screenshot({path:info.outputPath('multi-profile-sketch.png')});await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await extrude(page,1);await expect(page.getByTestId('model-volume')).toHaveText('14214.602 mm³');await extrude(page,3);await expect(page.getByTestId('model-volume')).toHaveText('15214.602 mm³');await page.getByRole('button',{name:'Sketch 1',exact:true}).click();await page.getByRole('button',{name:'Select circle 5',exact:true}).press('Enter');await page.getByLabel('Entity radius',{exact:true}).fill('4');await page.getByRole('button',{name:'Set entity dimensions',exact:true}).click();await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('15497.345 mm³');await page.screenshot({path:info.outputPath('multi-region-solid.png')});await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.reload();await expect(page.getByTestId('model-volume')).toHaveText('15497.345 mm³');await expect(page.getByRole('alert')).toHaveCount(0)
})
test('line and three-point arc form an exact curved region with local undo and redo',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Clear sketch',exact:true}).click();await page.getByRole('button',{name:'Line',exact:true}).click();await click(page,-5,0);await click(page,5,0);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Arc',exact:true}).click();await click(page,5,0);await click(page,0,5);await click(page,-5,0);await expect(page.locator('.sketch-state')).toContainText('2 entities');await page.getByRole('button',{name:'Undo sketch',exact:true}).click();await expect(page.locator('.sketch-state')).toContainText('1 entities');await page.getByRole('button',{name:'Redo sketch',exact:true}).click();await expect(page.locator('.sketch-state')).toContainText('2 entities');await page.getByRole('button',{name:'Select',exact:true}).click();await page.getByRole('button',{name:'Select arc 2',exact:true}).press('Enter');await page.getByRole('button',{name:'Delete entities',exact:true}).click();await expect(page.locator('.sketch-state')).toContainText('1 entities');await page.getByRole('button',{name:'Undo sketch',exact:true}).click();await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await extrude(page,1);await expect(page.getByTestId('model-volume')).toHaveText('392.699 mm³')
})

test('multi-entity rectangle drag accepts exact Tab dimensions before pointer release',async({page})=>{await open(page);await page.getByRole('button',{name:'Clear sketch',exact:true}).click();await page.getByRole('button',{name:'Rectangle',exact:true}).click();const a=await point(page,0,0),b=await point(page,25,12);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:4});await page.keyboard.press('Tab');const width=page.getByLabel('Draw width',{exact:true});await expect(width).toBeFocused();await width.fill('32');await width.press('Tab');await page.getByLabel('Draw height',{exact:true}).fill('18');await page.mouse.up();await page.getByLabel('Draw height',{exact:true}).press('Enter');await expect(page.locator('.sketch-state')).toContainText('4 entities');await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await extrude(page,1);await expect(page.getByTestId('model-volume')).toHaveText('5760.000 mm³')})

test('six-face cube follows signed views and supports drag rotation',async({page},info)=>{await open(page);await page.getByRole('button',{name:'Cancel sketch',exact:true}).click();const widget=page.getByRole('navigation',{name:'View orientation'});for(const [axis,view] of [['+X','Right'],['−X','Left'],['+Y','Back'],['−Y','Front'],['+Z','Top'],['−Z','Bottom']]){await page.getByLabel('Standard view',{exact:true}).selectOption(view);const face=widget.getByRole('button',{name:view.toUpperCase(),exact:true});await expect(face).toHaveAttribute('data-axis',axis);await face.click();await expect(face).toHaveAttribute('aria-pressed','true')}await widget.getByRole('button',{name:'Home view',exact:true}).click();const cube=page.getByLabel('Drag view cube to rotate',{exact:true}),box=await cube.boundingBox(),before=await cube.locator('polygon').first().getAttribute('points');await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2);await page.mouse.down();await page.mouse.move(box!.x+box!.width/2+45,box!.y+box!.height/2+22,{steps:8});await page.mouse.up();await expect(page.getByLabel('Standard view',{exact:true})).toHaveValue('Custom');expect(await cube.locator('polygon').first().getAttribute('points')).not.toBe(before);await widget.getByRole('button',{name:'Rotate cube left',exact:true}).click();await page.screenshot({path:info.outputPath('rotating-six-face-cube.png')});await widget.getByRole('button',{name:'Home view',exact:true}).click();await expect(page.getByLabel('Standard view',{exact:true})).toHaveValue('Isometric');expect((await widget.boundingBox())!.width).toBeLessThan(125)})

test('model hierarchy collapses groups, shows dependencies, renames features and hides bodies',async({page},info)=>{await open(page);await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await extrude(page,1);await expect(page.getByTestId('model-volume')).toHaveText('15000.000 mm³');const tree=page.getByRole('tree',{name:'Model hierarchy'});await expect(tree.getByRole('button',{name:'Origin',exact:true})).toHaveAttribute('aria-expanded','true');await tree.getByRole('button',{name:'Origin',exact:true}).click();await expect(tree.getByRole('button',{name:'XY plane',exact:true})).toHaveCount(0);await tree.getByRole('button',{name:'Origin',exact:true}).click();await tree.getByRole('button',{name:'Expand references for Extrude 1',exact:true}).click();await expect(tree.getByRole('button',{name:'Edit dependency Sketch 1',exact:true})).toBeVisible();await tree.getByRole('button',{name:'Rename Extrude 1',exact:true}).click();await page.getByRole('dialog',{name:'Rename feature'}).getByLabel('Feature name',{exact:true}).fill('Base plate');await page.getByRole('dialog',{name:'Rename feature'}).getByRole('button',{name:'Rename',exact:true}).click();await expect(tree.getByRole('button',{name:'Base plate',exact:true})).toBeVisible();await tree.getByRole('button',{name:'Hide body Base plate',exact:true}).click();await expect(tree.getByRole('button',{name:'Show body Base plate',exact:true})).toBeVisible();await expect(page.getByTestId('model-volume')).toHaveText('15000.000 mm³');await tree.getByRole('button',{name:'Show body Base plate',exact:true}).click();await tree.getByRole('button',{name:'Select body Base plate',exact:true}).click();await page.screenshot({path:info.outputPath('cad-model-hierarchy.png')});await page.reload();await expect(page.getByRole('button',{name:'Base plate',exact:true})).toBeVisible()})
