import {test,expect,type Page} from '@playwright/test'
async function start(page:Page){await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click()}
async function at(page:Page,x:number,y:number){return page.getByRole('img',{name:'Multi-profile sketch drawing surface'}).evaluate((el,p)=>{const svg=el as SVGSVGElement,out=new DOMPoint(Number(svg.dataset.originX)+p[0]*Number(svg.dataset.scale),Number(svg.dataset.originY)-p[1]*Number(svg.dataset.scale)).matrixTransform(svg.getScreenCTM()!);return {x:out.x,y:out.y}},[x,y])}
test('direct point tool, signed dimensions, conflicts, history, extrusion and reload',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page)
 await page.getByRole('button',{name:'Point',exact:true}).click();const pos=await at(page,60,20);await page.mouse.move(pos.x,pos.y);await page.keyboard.press('Tab')
 await page.getByLabel('Draw x',{exact:true}).fill('60');await page.getByLabel('Draw y',{exact:true}).fill('20');await page.getByRole('button',{name:'Place geometry',exact:true}).click()
 await expect(page.locator('.sketch-state')).toContainText('5 entities');await expect(page.locator('.sketch-state')).toContainText('1 regions')
 await page.getByRole('button',{name:'Origin / axes',exact:true}).click();await page.getByLabel('Constraint type',{exact:true}).selectOption('coordinate-x');await page.getByLabel('Constraint value',{exact:true}).fill('-12');await page.getByRole('button',{name:'Add constraint',exact:true}).click()
 await expect(page.getByRole('list',{name:'Sketch constraints'})).toContainText('X distance from origin')
 await page.getByRole('button',{name:'Select sketch X axis',exact:true}).press('Enter');await expect(page.getByLabel('Constraint type',{exact:true})).toHaveValue('coordinate-y');await page.getByRole('button',{name:'Add constraint',exact:true}).click()
 await expect(page.locator('.sketch-state')).toContainText('6 constraints')
 await page.getByRole('button',{name:'Select sketch origin',exact:true}).press('Enter');await page.getByRole('button',{name:'Add constraint',exact:true}).click();await expect(page.getByRole('alert')).toContainText(/conflict/i)
 await page.getByRole('button',{name:'Undo sketch',exact:true}).click();await expect(page.locator('.sketch-state')).toContainText('5 constraints');await page.getByRole('button',{name:'Redo sketch',exact:true}).click();await expect(page.locator('.sketch-state')).toContainText('6 constraints')
 await page.getByRole('button',{name:'Close constraint tools',exact:true}).click();await page.getByRole('button',{name:'Select point 5',exact:true}).press('Enter');await expect(page.getByLabel('Entity point x')).toHaveValue('-12');await expect(page.getByLabel('Entity point y')).toHaveValue('0')
 await expect(page.getByRole('button',{name:'Edit X coordinate dimension'})).toBeVisible({timeout:2000});await page.getByRole('button',{name:'Edit X coordinate dimension'}).press('Enter');await page.getByLabel('Coordinate dimension value').fill('-14');await page.getByRole('button',{name:'Set coordinate dimension',exact:true}).click();await expect(page.getByLabel('Entity point x')).toHaveValue('-14');await page.screenshot({path:info.outputPath('point-dimensions.png')});await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByLabel('Distance',{exact:true}).fill('16');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('24000.000 mm³')
 await page.reload();await expect(page.getByTestId('model-volume')).toHaveText('24000.000 mm³');await page.getByRole('button',{name:'Sketch 1',exact:true}).click();await page.getByRole('button',{name:'Select point 5',exact:true}).press('Enter');await expect(page.getByLabel('Entity point x')).toHaveValue('-14');expect(errors).toEqual([])
})
test('direct line chain accepts length and angle and anchors its endpoint at the origin',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page);await page.getByRole('button',{name:'Line',exact:true}).click();await page.getByRole('button',{name:'Clear sketch',exact:true}).click()
 const a=await at(page,0,0),b=await at(page,20,5);await page.mouse.click(a.x,a.y);await page.mouse.move(b.x,b.y);await page.keyboard.press('Tab')
 await page.getByLabel('Line input mode').selectOption('polar');await page.getByLabel('Draw length',{exact:true}).fill('25');await page.getByLabel('Draw angle',{exact:true}).fill('0');await page.getByRole('button',{name:'Place geometry',exact:true}).click();await page.keyboard.press('Escape')
 await page.getByRole('button',{name:'Select line 1',exact:true}).press('Enter');await expect(page.getByLabel('Entity end x')).toHaveValue('25')
 await page.getByRole('button',{name:'Select sketch origin',exact:true}).press('Enter');await page.getByRole('button',{name:'Add constraint',exact:true}).click();await expect(page.getByRole('list',{name:'Sketch constraints'})).toContainText('Coincident with origin')
 await page.getByLabel('Constraint type',{exact:true}).selectOption('horizontal');await page.getByRole('button',{name:'Add constraint',exact:true}).click();await expect(page.getByTestId('constraint-status')).toContainText('1 degrees of freedom')
 await page.getByLabel('Constraint type',{exact:true}).selectOption('length');await page.getByLabel('Constraint value',{exact:true}).fill('25');await page.getByRole('button',{name:'Add constraint',exact:true}).click();await expect(page.getByTestId('constraint-status')).toHaveText('Fully constrained')
 await page.screenshot({path:info.outputPath('origin-line.png')});await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Sketch 1',exact:true}).click();await page.getByRole('button',{name:'Constrain sketch',exact:true}).click();await expect(page.getByRole('list',{name:'Sketch constraints'})).toContainText('Coincident with origin');expect(errors).toEqual([])
})

test('face-attached point origin follows an upstream extrusion edit',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page);await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await page.getByRole('button',{name:'Extrude',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('24000.000 mm³')
 await page.getByRole('button',{name:'TOP',exact:true}).click();const canvas=page.getByLabel('3D model viewport. Drag to orbit, right-drag to pan, scroll to zoom.',{exact:true}),box=await canvas.boundingBox();await canvas.click({position:{x:box!.width/2,y:box!.height/2}});await page.getByRole('button',{name:'Sketch on face',exact:true}).click()
 await page.getByRole('button',{name:'Point',exact:true}).click();await page.getByRole('button',{name:'Clear sketch',exact:true}).click();const pos=await at(page,25,15);await page.mouse.click(pos.x,pos.y);await expect(page.locator('.sketch-state')).toContainText('1 entities');await page.getByRole('button',{name:'Origin / axes',exact:true}).click();await page.getByRole('button',{name:'Add constraint',exact:true}).click();await expect(page.getByTestId('constraint-status')).toHaveText('Fully constrained')
 await page.getByText('Sketch coordinate system',{exact:true}).click();await expect(page.locator('.sketch-frame-info')).toContainText('16.000 mm');await page.screenshot({path:info.outputPath('face-point-frame.png')});await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Extrude 1',exact:true}).click();await page.getByLabel('Distance',{exact:true}).fill('25');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByTestId('model-volume')).toHaveText('37500.000 mm³');await page.reload();await expect(page.getByTestId('model-volume')).toHaveText('37500.000 mm³');await page.getByRole('button',{name:'Sketch 2',exact:true}).click();await page.getByText('Sketch coordinate system',{exact:true}).click();await expect(page.locator('.sketch-frame-info')).toContainText('25.000 mm');await page.getByRole('button',{name:'Select point 1',exact:true}).press('Enter');await expect(page.getByLabel('Entity point x')).toHaveValue('0');await expect(page.getByLabel('Entity point y')).toHaveValue('0');expect(errors).toEqual([])
})
