import {test,expect} from '@playwright/test'
test('Move and Mirror are directly available for a primitive sketch and preserve exact editable geometry',async({page},info)=>{
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await expect(page.getByRole('button',{name:'Mirror sketch',exact:true})).toBeVisible();await page.getByRole('button',{name:'Move sketch',exact:true}).click();await page.getByLabel('Sketch move X',{exact:true}).fill('12');await page.getByLabel('Sketch move Y',{exact:true}).fill('8');await page.getByRole('button',{name:'Move selection',exact:true}).click();await expect(page.locator('.sketch-state')).toContainText('4 entities');await page.getByRole('button',{name:'Select line 1',exact:true}).press('Enter');await expect(page.getByLabel('Entity start x',{exact:true})).toHaveValue('12');await expect(page.getByLabel('Entity start y',{exact:true})).toHaveValue('8');await page.getByRole('button',{name:'Undo sketch',exact:true}).click();await page.getByRole('button',{name:'Redo sketch',exact:true}).click();const positions=await page.getByRole('img',{name:'Multi-profile sketch drawing surface'}).evaluate(el=>{const s=el as SVGSVGElement;return [[37,23],[42,27]].map(p=>{const out=new DOMPoint(Number(s.dataset.originX)+p[0]*Number(s.dataset.scale),Number(s.dataset.originY)-p[1]*Number(s.dataset.scale)).matrixTransform(s.getScreenCTM()!);return {x:out.x,y:out.y}})});await page.mouse.move(positions[0].x,positions[0].y);await page.mouse.down();await page.mouse.move(positions[1].x,positions[1].y,{steps:5});await page.mouse.up();await page.getByRole('button',{name:'Select line 1',exact:true}).press('Enter');await expect(page.getByLabel('Entity start x',{exact:true})).toHaveValue('17');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Mirror sketch',exact:true}).click();await page.getByLabel('Sketch mirror axis',{exact:true}).selectOption('Y');await page.getByRole('button',{name:'Mirror selection',exact:true}).click();await expect(page.locator('.sketch-state')).toContainText('8 entities');await expect(page.locator('.sketch-state')).toContainText('2 regions');await page.getByRole('button',{name:'Fit sketch',exact:true}).click();await page.screenshot({path:info.outputPath('moved-mirrored-sketch.png')});await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Sketch 1',exact:true}).click();await expect(page.locator('.sketch-state')).toContainText('8 entities')
})


test('sketch move has axis handles, Tab exact entry, safe cancellation and explicit selection',async({page},info)=>{
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByRole('button',{name:'Move sketch',exact:true}).click();
 const x=page.getByRole('button',{name:'Drag sketch X',exact:true});await expect(x).toBeVisible();
 const b=await x.boundingBox();await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2);await page.mouse.down();await page.mouse.move(b!.x+b!.width/2+36,b!.y+b!.height/2-20,{steps:4});await page.keyboard.press('Tab');await page.mouse.up();
 await expect(page.getByLabel('Sketch move X',{exact:true})).toBeFocused();await page.getByLabel('Sketch move X',{exact:true}).fill('12');await page.getByLabel('Sketch move Y',{exact:true}).fill('-8');await page.getByRole('button',{name:'Move selection',exact:true}).click();
 await page.getByRole('button',{name:'Select line 1',exact:true}).press('Enter');await expect(page.getByLabel('Entity start x',{exact:true})).toHaveValue('12');await expect(page.getByLabel('Entity start y',{exact:true})).toHaveValue('-8');
 await page.getByRole('button',{name:'Select all sketch entities',exact:true}).click();await page.getByRole('button',{name:'Move sketch',exact:true}).click();const y=await page.getByRole('button',{name:'Drag sketch Y',exact:true}).boundingBox();await page.mouse.move(y!.x+y!.width/2,y!.y+y!.height/2);await page.mouse.down();await page.mouse.move(y!.x+y!.width/2+30,y!.y+y!.height/2-25,{steps:4});await page.keyboard.press('Escape');await page.mouse.up();
 await page.getByRole('button',{name:'Select line 1',exact:true}).press('Enter');await expect(page.getByLabel('Entity start x',{exact:true})).toHaveValue('12');await expect(page.getByLabel('Entity start y',{exact:true})).toHaveValue('-8');
 await page.getByRole('button',{name:'Select all sketch entities',exact:true}).click();await page.getByRole('button',{name:'Move sketch',exact:true}).click();await page.screenshot({path:info.outputPath('sketch-move-handles.png')});await page.getByRole('button',{name:'Cancel transform',exact:true}).click();
 await page.getByRole('button',{name:'Clear sketch selection',exact:true}).click();await expect(page.locator('.sketch-state')).toContainText('0 selected');await page.getByRole('button',{name:'Undo sketch',exact:true}).click();await page.getByRole('button',{name:'Select line 1',exact:true}).press('Enter');await expect(page.getByLabel('Entity start x',{exact:true})).toHaveValue('0');await page.getByRole('button',{name:'Redo sketch',exact:true}).click();await page.getByRole('button',{name:'Finish sketch',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Sketch 1',exact:true}).click();await page.getByRole('button',{name:'Select line 1',exact:true}).press('Enter');await expect(page.getByLabel('Entity start x',{exact:true})).toHaveValue('12');
})


test('circle selection supports axis and free dragging, box selection and blank click clearing',async({page})=>{
 await page.goto('/#projects');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Create sketch',exact:true}).click();await page.getByRole('button',{name:'Sketch on XY plane',exact:true}).click();await page.getByRole('button',{name:'More sketch tools',exact:true}).click();await page.getByRole('button',{name:'Clear sketch',exact:true}).click();
 const surface=page.getByRole('img',{name:'Multi-profile sketch drawing surface'});
 const point=async(x:number,y:number)=>surface.evaluate((el,p)=>{const s=el as SVGSVGElement;const q=new DOMPoint(Number(s.dataset.originX)+p[0]*Number(s.dataset.scale),Number(s.dataset.originY)-p[1]*Number(s.dataset.scale)).matrixTransform(s.getScreenCTM()!);return {x:q.x,y:q.y}},[x,y]);
 for(const cx of [20,60]){await page.getByRole('toolbar',{name:'Sketch tools'}).getByRole('button',{name:'Circle',exact:true}).click();const a=await point(cx,20),b=await point(cx+5,20);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:4});await page.mouse.up()}
 await page.getByRole('button',{name:'Select',exact:true}).click();await page.getByRole('button',{name:'Select circle 1',exact:true}).press('Enter');await expect(page.getByRole('button',{name:'Select circle 1',exact:true})).toHaveAttribute('aria-pressed','true');
 const dragHandle=async(name:string,dx:number,dy:number)=>{const b=await page.getByRole('button',{name,exact:true}).boundingBox(),a=await point(0,0),z=await point(dx,dy);await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2);await page.mouse.down();await page.mouse.move(b!.x+b!.width/2+z.x-a.x,b!.y+b!.height/2+z.y-a.y,{steps:5});await page.mouse.up()};
 await page.getByRole('button',{name:'Move sketch',exact:true}).click();await dragHandle('Drag sketch Y',8,10);await expect(page.getByLabel('Entity center x',{exact:true})).toHaveValue('20');await expect(page.getByLabel('Entity center y',{exact:true})).toHaveValue('30');
 await page.getByRole('button',{name:'Move sketch',exact:true}).click();await dragHandle('Drag sketch freely',5,-5);await expect(page.getByLabel('Entity center x',{exact:true})).toHaveValue('25');await expect(page.getByLabel('Entity center y',{exact:true})).toHaveValue('25');
 await page.getByRole('button',{name:'Select circle 2',exact:true}).press('Shift+Enter');await expect(page.locator('.sketch-state')).toContainText('2 selected');
 const blank=await point(-10,50);await page.mouse.click(blank.x,blank.y);await expect(page.locator('.sketch-state')).toContainText('0 selected');const a=await point(10,10),b=await point(70,40);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:5});await page.mouse.up();await expect(page.locator('.sketch-state')).toContainText('2 selected');
 await page.getByRole('button',{name:'Select circle 2',exact:true}).press('Enter');await expect(page.getByLabel('Entity center x',{exact:true})).toHaveValue('60');await expect(page.getByLabel('Entity center y',{exact:true})).toHaveValue('20');
 const edge=await point(65,20),end=await point(68,22);await page.mouse.move(edge.x,edge.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:4});await page.mouse.up();await expect(page.getByLabel('Entity center x',{exact:true})).toHaveValue('63');await expect(page.getByLabel('Entity center y',{exact:true})).toHaveValue('22');
})
