import { sketchRegions, circularPlacement } from '../cad/sketch-entities'
import { holeFieldActive, toolFields, type AdvancedTool } from '../commands/feature-tools'
import type { CadDocument, ModelResult, LoftSection } from '../cad/types'
export function FeatureFields({tool,values,onChange,document:doc,model}:{tool:AdvancedTool;values:Record<string,string>;onChange:(key:string,value:string)=>void;document:CadDocument;model:ModelResult|null}){
 return <>{toolFields[tool].map(field=>{
  if(tool==='hole'&&!holeFieldActive(field.key,values))return null
  if(tool==='hole'&&values.termination==='through-all'&&field.key==='depth')return null
  if(tool==='hole'&&values.profileId&&['plane','x','y','diameter'].includes(field.key))return null
  if(field.key==='bodyId'&&['revolve','loft','sweep','box','cylinder','sphere'].includes(tool)&&values.operation==='new')return null
  if(tool==='split'&&values.planeId&&['plane','offset'].includes(field.key))return null
  if(field.kind==='sections')return <LoftSections key={field.key} value={values.sections??'[]'} onChange={value=>onChange('sections',value)} document={doc}/>
  let options:{value:string;label:string}[]|null=null
  if(field.kind==='region'){const sk=doc.features.find(f=>f.id===values.profileId);if(sk?.type!=='sketch'||!sk.parameters.entities)return null;try{options=sketchRegions(sk.parameters.entities).map((r,i)=>({value:r.id,label:'Region '+(i+1)}))}catch{options=[]}}
  if(field.kind==='hole-style')options=[{value:'simple',label:'Simple'},{value:'counterbore',label:'Counterbore'},{value:'countersink',label:'Countersink'}]
  if(field.kind==='hole-termination')options=[{value:'blind',label:'Blind'},{value:'through-all',label:'Through all'}]
  if(field.kind==='keep')options=[{value:'both',label:'Both sides — separate bodies'},{value:'positive',label:'Positive normal side'},{value:'negative',label:'Negative normal side'}]
  if(field.kind==='reference-plane')options=[{value:'',label:'Origin plane + offset'},...doc.features.filter(f=>f.type==='plane').map(f=>({value:f.id,label:f.name}))]
  if(field.kind==='axis')options=['X','Y','Z'].map(value=>({value,label:value}))
  if(field.kind==='plane')options=['XY','XZ','YZ'].map(value=>({value,label:value}))
  if(field.kind==='body'||field.kind==='tools')options=(model?.bodies??[]).filter(b=>field.kind!=='tools'||b.id!==values.bodyId).map(b=>({value:b.id,label:b.name}))
  if(field.kind==='path')options=doc.features.filter(f=>f.type==='sketch'&&f.id!==values.profileId&&f.parameters.entities).map(f=>({value:f.id,label:f.name}))
  if(field.kind==='profile')options=doc.features.filter(f=>f.type==='sketch'&&(tool!=='hole'||!!circularPlacement(f.parameters))).map(f=>({value:f.id,label:f.name}))
  if(field.kind==='operation')options=(tool==='combine'?['join','cut','intersect']:['new','join','cut','intersect']).map(value=>({value,label:{new:'New body',join:'Join',cut:'Cut',intersect:'Intersect'}[value]!}))
  if(field.kind==='boolean')return <label className="field checkbox-field" key={field.key}><span><input type="checkbox" checked={values[field.key]==='true'} onChange={e=>onChange(field.key,String(e.target.checked))}/>{field.label}</span></label>
  if(field.kind==='tools')return <fieldset className="body-tools" key={field.key}><legend>{field.label}</legend>{options?.map(option=><label key={option.value}><input type="checkbox" checked={values[field.key]?.split(',').includes(option.value)??false} onChange={e=>{const ids=new Set(values[field.key]?.split(',').filter(Boolean));if(e.target.checked)ids.add(option.value);else ids.delete(option.value);onChange(field.key,[...ids].join(','))}}/>{option.label}</label>)}</fieldset>
  return <label className="field" key={field.key}><span>{field.label}<small>{field.kind==='length'?doc.unit:field.kind==='angle'?'deg':''}</small></span>{options?<select aria-label={field.label} value={values[field.key]??''} onChange={e=>onChange(field.key,e.target.value)}>{field.kind!=='reference-plane'&&<option value="" disabled={tool!=='hole'||field.key!=='profileId'}>{tool==='hole'&&field.key==='profileId'?'Face position':'Choose…'}</option>}{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input aria-label={field.label} value={values[field.key]??''} onChange={e=>onChange(field.key,e.target.value)} spellCheck={false}/>}</label>
 })}{tool==='split'&&<p className="field-help">Split with an offset XY/XZ/YZ plane or an existing reference plane. XY normal is +Z, XZ is −Y, YZ is +X. Keep both sides creates separately selectable bodies; the first retained piece keeps the original body identity.</p>}{tool==='rotate'&&<p className="field-help">Rotate around an X, Y or Z axis through the pivot coordinates. Positive angles follow the right-hand rule. Create copy retains the source body.</p>}{tool==='scale'&&<p className="field-help">Uniform scale around the pivot coordinates: 0.5 halves each dimension; 2 doubles it. Create copy retains the original. Nonuniform scaling is not yet available.</p>}{['box','cylinder','sphere'].includes(tool)&&<p className="field-help">{tool==='box'?'Origin is the minimum XYZ corner. Width follows X, depth Y, height Z.':tool==='cylinder'?'Origin is the base center. Height follows the positive selected axis.':'Origin is the sphere center.'} Choose New body or a Boolean operation on a target body.</p>}{tool==='loft'&&<p className="field-help">Choose 2–16 sketch sections in travel order. Each section needs one closed contour without holes. Ruled transitions connect sections with straight spans; turn it off for smooth transitions. Guides and tangent conditions are not yet available.</p>}{tool==='sweep'&&<p className="field-help">Choose a closed profile and a separate open line/arc sketch path. Place the profile at the start of the path, perpendicular to its direction. Path segments must meet tangentially; mark helper lines as construction.</p>}{tool==='move'&&<p className="field-help">Drag the red X, green Y or blue Z arrow. Press Tab while dragging to enter an exact offset. Negative values move in the opposite direction. Preview frames the result; Apply saves the move in history.</p>}{tool==='gear'&&<p className="field-help">Involute spur profile · 20° default · radial root relief. Smooth involute B-spline flanks with analytic tip and root arcs.</p>}{tool==='hole'&&<p className="field-help">Depth is measured inward from the start plane. Recess depth starts at the same plane; a countersink angle is the included cone angle. A placement sketch supplies its circle diameter. Threads are not modeled.</p>}{['shell','draft'].includes(tool)&&<p className="field-help">Select the planar face to {tool==='shell'?'remove':'draft'} in the viewport before previewing.</p>}{tool==='chamfer'&&<p className="field-help">Select one or more edges on the target body.</p>}</>
}

function LoftSections({value,onChange,document:doc}:{value:string;onChange:(value:string)=>void;document:CadDocument}){
 let sections:LoftSection[];try{sections=JSON.parse(value)}catch{sections=[]}
 const change=(next:LoftSection[])=>onChange(JSON.stringify(next)),sketches=doc.features.filter(f=>f.type==='sketch')
 return <fieldset className="loft-sections"><legend>Loft sections · in order</legend>{sections.map((section,index)=>{
  const sketch=sketches.find(f=>f.id===section.profileId);let regions:{id:string}[]=[];try{regions=sketch?.parameters.entities?sketchRegions(sketch.parameters.entities):[]}catch{/* Invalid contours are explained by the kernel preview. */}
  return <div className="loft-section" key={index}><label className="field"><span>Section {index+1}</span><select aria-label={'Loft section '+(index+1)} value={section.profileId} onChange={e=>change(sections.map((s,i)=>i===index?{profileId:e.target.value}:s))}><option value="" disabled>Choose sketch…</option>{sketches.map(s=><option key={s.id} value={s.id} disabled={sections.some((v,i)=>i!==index&&v.profileId===s.id)}>{s.name}</option>)}</select></label>{sketch?.parameters.entities&&<label className="field"><span>Closed region</span><select aria-label={'Loft region '+(index+1)} value={section.regionId??''} onChange={e=>change(sections.map((s,i)=>i===index?{...s,regionId:e.target.value}:s))}><option value="">{regions.length===1?'Only closed region':'Choose region…'}</option>{regions.map((r,i)=><option key={r.id} value={r.id}>Region {i+1}</option>)}</select></label>}<div className="loft-section-actions"><button type="button" aria-label={'Move section '+(index+1)+' up'} disabled={index===0} onClick={()=>{const next=[...sections];[next[index-1],next[index]]=[next[index],next[index-1]];change(next)}}>↑ Up</button><button type="button" aria-label={'Move section '+(index+1)+' down'} disabled={index===sections.length-1} onClick={()=>{const next=[...sections];[next[index+1],next[index]]=[next[index],next[index+1]];change(next)}}>↓ Down</button><button type="button" aria-label={'Remove section '+(index+1)} disabled={sections.length<=2} onClick={()=>change(sections.filter((_,i)=>i!==index))}>Remove</button></div></div>
 })}<button className="button full" type="button" disabled={sections.length>=16||sections.length>=sketches.length} onClick={()=>{const next=sketches.find(s=>!sections.some(v=>v.profileId===s.id));if(next)change([...sections,{profileId:next.id}])}}>Add section</button></fieldset>
}
