import {useRef} from 'react'
import {House,ChevronLeft,ChevronRight,ChevronUp,ChevronDown} from 'lucide-react'
import {Vector3} from 'three'
import type {CameraOrientation,ViewName} from './Viewport'
const sides:{name:ViewName;axis:string;normal:number[];points:number[][]}[]=[
 {name:'Top',axis:'+Z',normal:[0,0,1],points:[[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]]},
 {name:'Bottom',axis:'−Z',normal:[0,0,-1],points:[[-1,-1,-1],[-1,1,-1],[1,1,-1],[1,-1,-1]]},
 {name:'Right',axis:'+X',normal:[1,0,0],points:[[1,-1,-1],[1,1,-1],[1,1,1],[1,-1,1]]},
 {name:'Left',axis:'−X',normal:[-1,0,0],points:[[-1,-1,-1],[-1,-1,1],[-1,1,1],[-1,1,-1]]},
 {name:'Front',axis:'−Y',normal:[0,-1,0],points:[[-1,-1,-1],[1,-1,-1],[1,-1,1],[-1,-1,1]]},
 {name:'Back',axis:'+Y',normal:[0,1,0],points:[[-1,1,-1],[-1,1,1],[1,1,1],[1,1,-1]]},
]
export function ViewCube({value,orientation,onChange,onOrbit}:{value:ViewName;orientation:CameraOrientation;onChange:(view:ViewName)=>void;onOrbit:(yaw:number,pitch:number)=>void}){
 const drag=useRef<{x:number;y:number;startX:number;startY:number;pointer:number;face?:ViewName}|null>(null),moved=useRef(false)
 const direction=new Vector3(...orientation.direction).normalize(),right=new Vector3(...orientation.up).cross(direction).normalize(),up=direction.clone().cross(right).normalize()
 const project=(p:number[])=>{const v=new Vector3(...p);return [64+v.dot(right)*29,62-v.dot(up)*29]}
 return <nav className="orientation-widget" aria-label="View orientation"><div className="cube-rotation-controls"><button className="cube-turn cube-turn-left" aria-label="Rotate cube left" title="Rotate 90° left" onClick={()=>onOrbit(-Math.PI/2,0)}><ChevronLeft size={12}/></button><button className="cube-turn cube-turn-right" aria-label="Rotate cube right" title="Rotate 90° right" onClick={()=>onOrbit(Math.PI/2,0)}><ChevronRight size={12}/></button><button className="cube-turn cube-turn-up" aria-label="Rotate cube up" title="Rotate 90° up" onClick={()=>onOrbit(0,-Math.PI/2)}><ChevronUp size={12}/></button><button className="cube-turn cube-turn-down" aria-label="Rotate cube down" title="Rotate 90° down" onClick={()=>onOrbit(0,Math.PI/2)}><ChevronDown size={12}/></button><svg viewBox="0 0 128 124" className="orientation-cube" aria-label="Drag view cube to rotate" onPointerDown={e=>{if(e.button!==0)return;moved.current=false;drag.current={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,pointer:e.pointerId,face:(e.target as Element).closest('[data-view]')?.getAttribute('data-view') as ViewName|undefined};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d||d.pointer!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(e.clientX-d.startX,e.clientY-d.startY)>3)moved.current=true;if(moved.current)onOrbit(-dx*.015,-dy*.015);d.x=e.clientX;d.y=e.clientY}} onPointerUp={e=>{const d=drag.current;if(!d)return;drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(!moved.current&&d.face)onChange(d.face)}} onPointerCancel={()=>{drag.current=null;moved.current=true}}>
 {sides.filter(face=>new Vector3(...face.normal).dot(direction)>.001).map(face=>{const points=face.points.map(project),center=points.reduce((s,p)=>[s[0]+p[0]/4,s[1]+p[1]/4],[0,0]);const radius=Math.min(...points.map((a,i)=>{const b=points[(i+1)%points.length],dx=b[0]-a[0],dy=b[1]-a[1];return Math.abs(dx*(center[1]-a[1])-dy*(center[0]-a[0]))/Math.max(.001,Math.hypot(dx,dy))})),fontSize=Math.min(16,radius*1.1);return <g key={face.name} role="button" tabIndex={0} aria-label={face.name.toUpperCase()} aria-pressed={value===face.name} data-axis={face.axis} data-coordinate={face.axis.at(-1)} data-view={face.name} className={value===face.name?'cube-face active':'cube-face'} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();onChange(face.name)}}}><title>{face.name+' view · '+face.axis}</title><polygon points={points.map(p=>p.join(',')).join(' ')}/><text className="cube-axis-label" style={{fontSize,visibility:fontSize>=9?'visible':'hidden'}} x={center[0]} y={center[1]+fontSize*.32}>{face.axis}</text></g>})}
 </svg></div><div className="orientation-caption"><button aria-label="Home view" title="Home view · isometric" onClick={()=>onChange('Isometric')}><House size={14}/></button></div></nav>
}
